server:
  port: 5050
spring:
  cloud:
    gateway:
#测试网关路由是否 OK
      routes: #配置路由, 可以有多个路由配置
            # 为家居网后台管理到 hspliving-service 的一组路由
        - id: wjwliving_service_route
          uri: lb://wjwliving-service
          predicates:
            - Path=/api/service/**
          filters:
            - RewritePath=/api/service/(?<segment>.*),/$\{segment}
        - id: wjwliving_commodity_route
          uri: lb://wjwliving-commodity
          predicates:
            - Path=/api/commodity/** # 这是一个更精确的路径，需要写在前面
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        - id: wjwliving_renren_fast_route #路由的 ID，程序员自己写,要求唯一
          uri: lb://renren-fast
          predicates:
            - Path=/api/** #断言,路径相匹配的进行路由,由前端统一传入api
          filters:
            - RewritePath=/api/(?<segment>.*), /renren-fast/$\{segment}

#将 wjwliving-gateway 注册到 nacos
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
  name: wjwliving-gateway

